//  FigmaProfileTestView.swift — LOCAL MCP TEST (do not commit; ETS-branded)
//  Generated by themekit-mcp design_to_code v2.11.1-dev from Figma node 25795-9030
//  (Login-register form), expandInstances. No manual edits.
import SwiftUI
import ThemeKit

struct FigmaProfileTestView: View {
    private var theme: Theme { Theme.shared }
    @State private var text = ""
    var body: some View {
        ScrollView {
// ⚠️ unmapped: Login-register form
VStack(alignment: .leading, spacing: Theme.SpacingKey.md.value) {
    // layout: Title with CTA
    HStack(spacing: Theme.SpacingKey.xl4.value) {
        // layout: Title
        HStack(spacing: Theme.SpacingKey.xs.value) {
            Text("Giriş Yap").textStyle(.headingXs).foregroundStyle(theme.background(.bgTertiary))
        }
        // ⚠️ unmapped: Buttons
        HStack(spacing: Theme.SpacingKey.xs.value) {
            Image(systemName: "chevron.right").foregroundStyle(theme.foreground(.fgHero)).accessibilityLabel("chevron-right")
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
    }
    // layout: Inputs
    VStack(alignment: .leading, spacing: Theme.SpacingKey.md.value) {
        TextInput("Input(default)", text: $text).controlSize(.large)
        // layout: Password
        VStack(alignment: .leading, spacing: Theme.SpacingKey.xs.value) {
            TextInput("Input Label", text: $text)
            // TODO: review (confidence 0.45)
            Card {
                HStack {
                    // ⚠️ unmapped: Main Elevator
                    HStack(spacing: Theme.SpacingKey.sm.value) {
                        // layout: Content
                        HStack {
                            Text("Şifre").textStyle(.bodyBase500).foregroundStyle(theme.text(.textTertiary))
                        }
                        Image(systemName: "eye.slash").foregroundStyle(theme.text(.textTertiary)).accessibilityLabel("eye-slash")
                    }
                    .padding(.horizontal, Theme.SpacingKey.sm.value)
                }
            }
            Text("This is a hint text to help user.").textStyle(.bodySm400).foregroundStyle(theme.text(.textTertiary))
        }
    }
    // layout: Remember Me Container
    HStack {
        Checkbox("Beni Hatırla", isChecked: .constant(false)).controlSize(.small)
        Spacer()
        // ⚠️ unmapped: Buttons
        HStack(spacing: Theme.SpacingKey.xs.value) {
            Text("Şifremi Unuttum").textStyle(.labelSm600).foregroundStyle(theme.foreground(.fgHero))
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
    }
    // ⚠️ unmapped: Buttons
    HStack(spacing: Theme.SpacingKey.sm.value) {
        Text("Giriş Yap").textStyle(.heading3xs).foregroundStyle(theme.foreground(.fgSecondary))
        Image(systemName: "arrow.right").foregroundStyle(theme.foreground(.fgSecondary)).accessibilityLabel("arrow-right")
    }
    .padding(.horizontal, Theme.SpacingKey.md.value)
    .padding(.vertical, Theme.SpacingKey.sm.value)
    .background(theme.foreground(.fgHero))
    .cornerRadius(Theme.RadiusKey.sm.value)
    DividerView("veya")
    // layout: Social Login Container
    HStack(alignment: .top, spacing: Theme.SpacingKey.md.value) {
        // ⚠️ unmapped: Social Buttons
        HStack(spacing: Theme.SpacingKey.sm.value) {
            Image("social-icons").accessibilityLabel("Social Icons")   // ⚠️ asset: add to the asset catalog (export URL in the report)
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
        // ⚠️ unmapped: Social Buttons
        HStack(spacing: Theme.SpacingKey.sm.value) {
            Image("social-icons").accessibilityLabel("Social Icons")   // ⚠️ asset: add to the asset catalog (export URL in the report)
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
        // ⚠️ unmapped: Social Buttons
        HStack(spacing: Theme.SpacingKey.sm.value) {
            Image("social-icons").accessibilityLabel("Social Icons")   // ⚠️ asset: add to the asset catalog (export URL in the report)
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
    }
    // layout: Sign Up Prompt
    HStack(spacing: Theme.SpacingKey.sm.value) {
        Text("Henüz hesabınız yok mu?").textStyle(.bodySm400).foregroundStyle(theme.background(.bgTertiary))
        // ⚠️ unmapped: Buttons
        HStack(spacing: Theme.SpacingKey.xs.value) {
            Text("Üye Olun").textStyle(.labelSm600).foregroundStyle(theme.foreground(.fgHero))
        }
        .cornerRadius(Theme.RadiusKey.sm.value)
    }
}
.padding(Theme.SpacingKey.md.value)
.background(theme.foreground(.fgSecondary))
.cornerRadius(Theme.RadiusKey.md.value)
        }
        .background(Color(.systemGroupedBackground))
        .navigationTitle("Figma → ThemeKit (MCP)")
        .navigationBarTitleDisplayMode(.inline)
    }
}
