//
//  ColorTokens.generated.swift
//  GlobalUIComponents
//  Created by İsa Mercan on 23.06.2026.
//
//  GENERATED from the Figma design system — do not edit by hand.
//  Token names are semantic / brand-agnostic.
//

import SwiftUI

extension Theme {
    public enum ForegroundColorKey: String, CaseIterable {
        case fgHero = "foreground.fg-hero"
        case fgSecondary = "foreground.fg-secondary"
        case fgTurquoise = "foreground.fg-turquoise"
        case badgeFgMaximumpink = "foreground.badge.fg-maximumpink"
        case badgeFgTurquoise = "foreground.badge.fg-turquoise"
        case badgeFgOrange = "foreground.badge.fg-orange"
        case systemcolorsFgSuccess = "foreground.systemcolors.fg-success"
        case systemcolorsFgError = "foreground.systemcolors.fg-error"
        case systemcolorsFgWarning = "foreground.systemcolors.fg-warning"
        case systemcolorsFgInfo = "foreground.systemcolors.fg-info"
    }

    public enum BackgroundColorKey: String, CaseIterable {
        case bgWhite = "background.bg-white"
        case bgHero = "background.bg-hero"
        case bgElevatorPrimary = "background.bg-elevator-primary"
        case bgElevatorTertiary = "background.bg-elevator-tertiary"
        case bgSecondary = "background.bg-secondary"
        case bgSecondaryLight = "background.bg-secondary-light"
        case bgTertiary = "background.bg-tertiary"
        case bgTurquoise = "background.bg-turquoise"
        case bgTurquoiseLight = "background.bg-turquoise-light"
        case bgOrange = "background.bg-orange"
        case badgeBgMaximumpinkBase = "background.badge.bg-maximumpink-base"
        case badgeBgMaximumpinkLight = "background.badge.bg-maximumpink-light"
        case badgeBgPurple = "background.badge.bg-purple"
        case badgeBgOrange = "background.badge.bg-orange"
        case badgeBgTurquoiseLight = "background.badge.bg-turquoise-light"
        case skeletonBgSkeletonBase = "background.skeleton.bg-skeleton-base"
        case systemcolorsBgSuccess = "background.systemcolors.bg-success"
        case systemcolorsBgSuccessLight = "background.systemcolors.bg-success-light"
        case systemcolorsBgError = "background.systemcolors.bg-error"
        case systemcolorsBgErrorLight = "background.systemcolors.bg-error-light"
        case systemcolorsBgWarning = "background.systemcolors.bg-warning"
        case systemcolorsBgWarningLight = "background.systemcolors.bg-warning-light"
        case systemcolorsBgInfo = "background.systemcolors.bg-info"
        case systemcolorsBgInfoLight = "background.systemcolors.bg-info-light"
    }

    public enum BorderColorKey: String, CaseIterable {
        case borderHero = "border.border-hero"
        case borderPrimary = "border.border-primary"
        case borderOrange = "border.border-orange"
        case borderTurquoise = "border.border-turquoise"
        case systemcolorsBorderSuccess = "border.systemcolors.border-success"
        case systemcolorsBorderSuccessLight = "border.systemcolors.border-success-light"
        case systemcolorsBorderError = "border.systemcolors.border-error"
        case systemcolorsBorderErrorLight = "border.systemcolors.border-error-light"
        case systemcolorsBorderWarning = "border.systemcolors.border-warning"
        case systemcolorsBorderWarningLight = "border.systemcolors.border-warning-light"
        case systemcolorsBorderInfo = "border.systemcolors.border-info"
        case systemcolorsBorderInfoLight = "border.systemcolors.border-info-light"
    }

    public enum TextColorKey: String, CaseIterable {
        case textPrimary = "text.text-primary"
        case textSecondary = "text.text-secondary"
        case textTertiary = "text.text-tertiary"
        case textDisabled = "text.text-disabled"
        case textHero = "text.text-hero"
        case textPurple = "text.text-purple"
        case textSecondaryInverse = "text.text-secondary-inverse"
    }

    public enum PaletteColorKey: String, CaseIterable {
        case primary50 = "palette.primary.50"
        case primary100 = "palette.primary.100"
        case primary200 = "palette.primary.200"
        case primary300 = "palette.primary.300"
        case primary400 = "palette.primary.400"
        case primary500 = "palette.primary.500"
        case primary600 = "palette.primary.600"
        case primary700 = "palette.primary.700"
        case primary800 = "palette.primary.800"
        case primary900 = "palette.primary.900"
        case neutral50 = "palette.neutral.50"
        case neutral100 = "palette.neutral.100"
        case neutral200 = "palette.neutral.200"
        case neutral300 = "palette.neutral.300"
        case neutral400 = "palette.neutral.400"
        case neutral500 = "palette.neutral.500"
        case neutral600 = "palette.neutral.600"
        case neutral700 = "palette.neutral.700"
        case neutral800 = "palette.neutral.800"
        case neutral900 = "palette.neutral.900"
        case info50 = "palette.info.50"
        case info100 = "palette.info.100"
        case info200 = "palette.info.200"
        case info300 = "palette.info.300"
        case info400 = "palette.info.400"
        case info500 = "palette.info.500"
        case info600 = "palette.info.600"
        case info700 = "palette.info.700"
        case info800 = "palette.info.800"
        case info900 = "palette.info.900"
        case success50 = "palette.success.50"
        case success100 = "palette.success.100"
        case success200 = "palette.success.200"
        case success300 = "palette.success.300"
        case success400 = "palette.success.400"
        case success500 = "palette.success.500"
        case success600 = "palette.success.600"
        case success700 = "palette.success.700"
        case success800 = "palette.success.800"
        case success900 = "palette.success.900"
        case warning50 = "palette.warning.50"
        case warning100 = "palette.warning.100"
        case warning200 = "palette.warning.200"
        case warning300 = "palette.warning.300"
        case warning400 = "palette.warning.400"
        case warning500 = "palette.warning.500"
        case warning600 = "palette.warning.600"
        case warning700 = "palette.warning.700"
        case warning800 = "palette.warning.800"
        case warning900 = "palette.warning.900"
        case error50 = "palette.error.50"
        case error100 = "palette.error.100"
        case error200 = "palette.error.200"
        case error300 = "palette.error.300"
        case error400 = "palette.error.400"
        case error500 = "palette.error.500"
        case error600 = "palette.error.600"
        case error700 = "palette.error.700"
        case error800 = "palette.error.800"
        case error900 = "palette.error.900"
        case turquoise50 = "palette.turquoise.50"
        case turquoise100 = "palette.turquoise.100"
        case turquoise200 = "palette.turquoise.200"
        case turquoise300 = "palette.turquoise.300"
        case turquoise400 = "palette.turquoise.400"
        case turquoise500 = "palette.turquoise.500"
        case turquoise600 = "palette.turquoise.600"
        case turquoise700 = "palette.turquoise.700"
        case turquoise800 = "palette.turquoise.800"
        case turquoise900 = "palette.turquoise.900"
        case orange50 = "palette.orange.50"
        case orange100 = "palette.orange.100"
        case orange200 = "palette.orange.200"
        case orange300 = "palette.orange.300"
        case orange400 = "palette.orange.400"
        case orange500 = "palette.orange.500"
        case orange600 = "palette.orange.600"
        case orange700 = "palette.orange.700"
        case orange800 = "palette.orange.800"
        case orange900 = "palette.orange.900"
        case purple50 = "palette.purple.50"
        case purple100 = "palette.purple.100"
        case purple200 = "palette.purple.200"
        case purple300 = "palette.purple.300"
        case purple400 = "palette.purple.400"
        case purple500 = "palette.purple.500"
        case purple600 = "palette.purple.600"
        case purple700 = "palette.purple.700"
        case purple800 = "palette.purple.800"
        case purple900 = "palette.purple.900"
        case pink50 = "palette.pink.50"
        case pink100 = "palette.pink.100"
        case pink200 = "palette.pink.200"
        case pink300 = "palette.pink.300"
        case pink400 = "palette.pink.400"
        case pink500 = "palette.pink.500"
        case pink600 = "palette.pink.600"
        case pink700 = "palette.pink.700"
        case pink800 = "palette.pink.800"
        case pink900 = "palette.pink.900"
    }
}
