#!/usr/bin/env python3
"""
Generate skills/themekit/references/components.md from the ThemeKit source.

A compact, always-accurate catalog for the Claude Code skill: every public
component grouped by Atom / Molecule / Organism, plus every chainable modifier.
Re-run with `make skill` (or `python3 tools/gen_skill.py`) so the reference can
never drift from the code.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / "Sources/ThemeKit/Components"
OUT = ROOT / "skills/themekit/references/components.md"
THEMES_SRC = ROOT / "Sources/ThemeKit/Theme/DaisyThemes.swift"
THEMES_OUT = ROOT / "skills/themekit/references/themes.md"
THEME_RE = re.compile(r'\.init\(\s*"(\w+)",\s*"([^"]+)"')

CATEGORIES = [("Atoms", "Atoms"), ("Molecules", "Molecules"), ("Organisms", "Organisms")]

# `public struct Name: View` / `public struct Name<...>: View`
STRUCT_RE = re.compile(r"^public struct (\w+)(?:<[^>]*>)?\s*:\s*View\b", re.M)
# self-returning chainable modifiers: `func name(...) -> Self`
MODIFIER_RE = re.compile(r"\bfunc (\w+)\s*\([^;{]*?\)\s*->\s*Self\b")
# first public init's leading parameter labels (a usage hint, best-effort)
INIT_RE = re.compile(r"public init\(\s*(.*?)\)\s*\{", re.S)


def param_labels(swift: str) -> str:
    m = INIT_RE.search(swift)
    if not m:
        return ""
    body = m.group(1)
    labels = []
    depth = 0
    token = ""
    # split top-level commas only (ignore commas inside <>, (), [])
    for ch in body:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            labels.append(token)
            token = ""
        else:
            token += ch
    labels.append(token)
    names = []
    for p in labels:
        p = p.strip()
        if not p:
            continue
        # `_ title: String` -> "title" (positional) ; `label: String` -> "label:"
        head = p.split(":")[0].strip()
        parts = head.split()
        if not parts:
            continue
        if parts[0] == "_":
            names.append(parts[1] if len(parts) > 1 else "_")
        else:
            names.append(parts[0] + ":")
    return ", ".join(names[:6]) + (" …" if len(names) > 6 else "")


def collect():
    out = {}
    all_modifiers = set()
    for label, folder in CATEGORIES:
        items = []
        base = COMPONENTS / folder
        for path in sorted(base.rglob("*.swift")):
            swift = path.read_text(encoding="utf-8")
            structs = STRUCT_RE.findall(swift)
            if not structs:
                continue
            mods = sorted(set(MODIFIER_RE.findall(swift)))
            all_modifiers.update(mods)
            primary = structs[0]
            primary_params = param_labels(swift)
            for name in structs:
                is_primary = name == primary
                items.append((name, primary_params if is_primary else "", mods if is_primary else []))
        out[label] = items
    return out, sorted(all_modifiers)


def render(cats, modifiers):
    total = sum(len(v) for v in cats.values())
    lines = [
        "<!-- GENERATED by tools/gen_skill.py — do not edit by hand. Run `make skill`. -->",
        "# ThemeKit component reference",
        "",
        f"{total} public SwiftUI components. Every one reads `@Environment(\\.theme)` and "
        "resolves all colors from tokens — **never hardcode a color**. Init shows the "
        "*required/common* params; long-tail styling is set with the chainable modifiers "
        "listed at the bottom.",
        "",
    ]
    for label, _ in CATEGORIES:
        items = cats[label]
        lines.append(f"## {label} ({len(items)})")
        lines.append("")
        for name, params, mods in items:
            sig = f"`{name}({params})`" if params else f"`{name}`"
            extra = f" — modifiers: {', '.join('`.' + m + '()`' for m in mods)}" if mods else ""
            lines.append(f"- {sig}{extra}")
        lines.append("")
    lines.append("## Chainable modifiers (all components)")
    lines.append("")
    lines.append("Set styling/variants/flags AFTER the init, SwiftUI-style:")
    lines.append("")
    lines.append(" ".join(f"`.{m}()`" for m in modifiers))
    lines.append("")
    lines.append("Plus the native cross-cuts every control honors: `.disabled(_:)`, "
                 "`.controlSize(_:)`, `.a11yID(_:)`.")
    lines.append("")
    return "\n".join(lines)


def render_themes():
    themes = THEME_RE.findall(THEMES_SRC.read_text(encoding="utf-8"))
    lines = [
        "<!-- GENERATED by tools/gen_skill.py — do not edit by hand. Run `make skill`. -->",
        "# ThemeKit daisyUI themes",
        "",
        f"{len(themes)} themes ported from daisyUI. Apply one live, or show them in a "
        "`ThemePicker` grid.",
        "",
        "```swift",
        'DaisyTheme.named("dracula")?.apply()          // recolor Theme.shared',
        'Theme.shared.apply(DaisyTheme.named("nord")!.config)',
        "",
        "@State private var active: String? = \"cupcake\"",
        "ThemePicker(selection: $active)               // grid of all themes",
        "```",
        "",
        "## Theme ids",
        "",
    ]
    lines += [f"- `{tid}` ({name})" for tid, name in themes]
    lines.append("")
    return "\n".join(lines), len(themes)


def main():
    cats, modifiers = collect()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(cats, modifiers), encoding="utf-8")
    total = sum(len(v) for v in cats.values())
    themes_md, n_themes = render_themes()
    THEMES_OUT.write_text(themes_md, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {total} components, {len(modifiers)} modifiers")
    print(f"Wrote {THEMES_OUT.relative_to(ROOT)} — {n_themes} daisyUI themes")


if __name__ == "__main__":
    main()
