#!/usr/bin/env python3
"""
Generate skills/themekit/references/components.md from the ThemeKit source.

A compact, always-accurate catalog for the Claude Code skill: every public
component grouped by Atom / Molecule / Organism, plus every chainable modifier.
Re-run with `make skill` (or `python3 tools/gen_skill.py`) so the reference can
never drift from the code.
"""
import re
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / "Sources/ThemeKit/Components"
OUT = ROOT / "skills/themekit/references/components.md"
THEMES_SRC = ROOT / "Sources/ThemeKit/Theme/DaisyThemes.swift"
THEMES_OUT = ROOT / "skills/themekit/references/themes.md"
LLMS_OUT = ROOT / "llms.txt"
JSON_OUT = ROOT / "mcp/themekit.json"
THEME_RE = re.compile(r'\.init\(\s*"(\w+)",\s*"([^"]+)"')

RULES = [
    "Read the theme via `@Environment(\\.theme) private var theme`; inject `.environment(Theme.shared)` once at the root.",
    "Never hardcode a color — use `theme.text(.textPrimary)`, `theme.background(.bgWhite)`, or a `SemanticColor`.",
    "Put required content/bindings/actions in `init`; set variants, sizes, flags, colors and callbacks with chainable modifiers.",
    "Sizes use `.controlSize(_:)`; disabled state uses `.disabled(_:)`; accessibility id uses `.a11yID(_:)`.",
    "Recolor everything with `Theme.shared.applyGenerated(primaryHex:)` or a daisyUI theme: `DaisyTheme.named(\"dracula\")?.apply()`.",
]

TOKENS = {
    "text": ["textPrimary", "textSecondary", "textTertiary", "textDisabled", "textHero"],
    "background": ["bgWhite", "bgElevatorPrimary", "bgSecondary", "bgSecondaryLight", "bgHero", "bgTertiary"],
    "border": ["borderPrimary", "borderHero"],
    "foreground": ["fgHero", "fgSecondary"],
    "semanticColor": ["primary", "secondary", "accent", "neutral", "info", "success", "warning", "error"],
    "fillVariant": ["solid", "soft", "outline", "ghost"],
    "radiusRole": ["box", "field", "selector"],
    "spacing": ["xs", "sm", "md", "base", "lg", "xl"],
}

CATEGORIES = [("Atoms", "Atoms"), ("Molecules", "Molecules"), ("Organisms", "Organisms")]

# `public struct Name: View` / `public struct Name<...>: View`
STRUCT_RE = re.compile(r"^public struct (\w+)(?:<[^>]*>)?\s*:\s*View\b", re.M)
# self-returning chainable modifiers: `func name(...) -> Self`
MODIFIER_RE = re.compile(r"\bfunc (\w+)\s*\([^;{]*?\)\s*->\s*Self\b")
# first public init's leading parameter labels (a usage hint, best-effort)
INIT_RE = re.compile(r"public init\(\s*(.*?)\)\s*\{", re.S)


def param_labels(swift: str) -> str:
    m = INIT_RE.search(swift)
    if not m:
        return ""
    body = m.group(1)
    labels = []
    depth = 0
    token = ""
    # split top-level commas only (ignore commas inside <>, (), [])
    for ch in body:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            labels.append(token)
            token = ""
        else:
            token += ch
    labels.append(token)
    names = []
    for p in labels:
        p = p.strip()
        if not p:
            continue
        # `_ title: String` -> "title" (positional) ; `label: String` -> "label:"
        head = p.split(":")[0].strip()
        parts = head.split()
        if not parts:
            continue
        if parts[0] == "_":
            names.append(parts[1] if len(parts) > 1 else "_")
        else:
            names.append(parts[0] + ":")
    return ", ".join(names[:6]) + (" …" if len(names) > 6 else "")


def collect():
    out = {}
    all_modifiers = set()
    for label, folder in CATEGORIES:
        items = []
        base = COMPONENTS / folder
        for path in sorted(base.rglob("*.swift")):
            swift = path.read_text(encoding="utf-8")
            structs = STRUCT_RE.findall(swift)
            if not structs:
                continue
            mods = sorted(set(MODIFIER_RE.findall(swift)))
            all_modifiers.update(mods)
            primary = structs[0]
            primary_params = param_labels(swift)
            for name in structs:
                is_primary = name == primary
                items.append((name, primary_params if is_primary else "", mods if is_primary else []))
        out[label] = items
    return out, sorted(all_modifiers)


def render(cats, modifiers):
    total = sum(len(v) for v in cats.values())
    lines = [
        "<!-- GENERATED by tools/gen_skill.py — do not edit by hand. Run `make skill`. -->",
        "# ThemeKit component reference",
        "",
        f"{total} public SwiftUI components. Every one reads `@Environment(\\.theme)` and "
        "resolves all colors from tokens — **never hardcode a color**. Init shows the "
        "*required/common* params; long-tail styling is set with the chainable modifiers "
        "listed at the bottom.",
        "",
    ]
    for label, _ in CATEGORIES:
        items = cats[label]
        lines.append(f"## {label} ({len(items)})")
        lines.append("")
        for name, params, mods in items:
            sig = f"`{name}({params})`" if params else f"`{name}`"
            extra = f" — modifiers: {', '.join('`.' + m + '()`' for m in mods)}" if mods else ""
            lines.append(f"- {sig}{extra}")
        lines.append("")
    lines.append("## Chainable modifiers (all components)")
    lines.append("")
    lines.append("Set styling/variants/flags AFTER the init, SwiftUI-style:")
    lines.append("")
    lines.append(" ".join(f"`.{m}()`" for m in modifiers))
    lines.append("")
    lines.append("Plus the native cross-cuts every control honors: `.disabled(_:)`, "
                 "`.controlSize(_:)`, `.a11yID(_:)`.")
    lines.append("")
    return "\n".join(lines)


def render_themes(themes):
    lines = [
        "<!-- GENERATED by tools/gen_skill.py — do not edit by hand. Run `make skill`. -->",
        "# ThemeKit daisyUI themes",
        "",
        f"{len(themes)} themes ported from daisyUI. Apply one live, or show them in a "
        "`ThemePicker` grid.",
        "",
        "```swift",
        'DaisyTheme.named("dracula")?.apply()          // recolor Theme.shared',
        'Theme.shared.apply(DaisyTheme.named("nord")!.config)',
        "",
        "@State private var active: String? = \"cupcake\"",
        "ThemePicker(selection: $active)               // grid of all themes",
        "```",
        "",
        "## Theme ids",
        "",
    ]
    lines += [f"- `{tid}` ({name})" for tid, name in themes]
    lines.append("")
    return "\n".join(lines), len(themes)


def render_llms(cats, modifiers, themes):
    total = sum(len(v) for v in cats.values())
    lines = [
        "# ThemeKit",
        "",
        f"> A token-driven, brand-neutral SwiftUI design system — {total} components, "
        "runtime theming, and the 32 daisyUI themes. Every color / radius / spacing / "
        "type style is a design token resolved at runtime from the active `Theme`; "
        "components never hardcode a color.",
        "",
        "Rules for generating ThemeKit code:",
        "- Read the theme via `@Environment(\\.theme) private var theme`; inject "
        "`.environment(Theme.shared)` once at the root. Never hardcode a color — use "
        "`theme.text(.textPrimary)`, `theme.background(.bgWhite)`, or a `SemanticColor`.",
        "- Put required content/bindings/actions in `init`; set variants, sizes, flags, "
        "colors and callbacks with chainable modifiers.",
        "- Sizes use `.controlSize(_:)`; disabled state uses `.disabled(_:)`.",
        "- Recolor everything with `Theme.shared.applyGenerated(primaryHex:)` or a "
        "daisyUI theme: `DaisyTheme.named(\"dracula\")?.apply()`.",
        "",
        "## Docs",
        "- [SKILL.md](skills/themekit/SKILL.md): idioms, setup, patterns, anti-patterns",
        "- [Components reference](skills/themekit/references/components.md): every component's init + modifiers",
        "- [Themes reference](skills/themekit/references/themes.md): the daisyUI theme catalog",
        "",
    ]
    for label, _ in CATEGORIES:
        names = ", ".join(f"`{n}`" for n, _, _ in cats[label])
        lines.append(f"## {label}")
        lines.append("")
        lines.append(names)
        lines.append("")
    lines.append("## Chainable modifiers")
    lines.append("")
    lines.append(" ".join(f"`.{m}()`" for m in modifiers))
    lines.append("")
    lines.append("## daisyUI themes")
    lines.append("")
    lines.append(", ".join(f"`{tid}`" for tid, _ in themes))
    lines.append("")
    return "\n".join(lines)


def render_json(cats, modifiers, themes):
    components = []
    for label, _ in CATEGORIES:
        for name, params, mods in cats[label]:
            components.append({
                "name": name,
                "category": label,
                "init": f"{name}({params})" if params else name,
                "modifiers": [f".{m}()" for m in mods],
            })
    return json.dumps({
        "name": "themekit",
        "summary": "A token-driven, brand-neutral SwiftUI design system. Every color / "
                   "radius / spacing / type style is a token resolved at runtime from the "
                   "active Theme; components never hardcode a color.",
        "rules": RULES,
        "tokens": TOKENS,
        "components": components,
        "modifiers": [f".{m}()" for m in modifiers],
        "themes": [{"id": t[0], "name": t[1]} for t in themes],
    }, indent=2)


def main():
    cats, modifiers = collect()
    themes = THEME_RE.findall(THEMES_SRC.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(cats, modifiers), encoding="utf-8")
    themes_md, n_themes = render_themes(themes)
    THEMES_OUT.write_text(themes_md, encoding="utf-8")
    LLMS_OUT.write_text(render_llms(cats, modifiers, themes), encoding="utf-8")
    if JSON_OUT.parent.exists():
        JSON_OUT.write_text(render_json(cats, modifiers, themes), encoding="utf-8")
    total = sum(len(v) for v in cats.values())
    print(f"Wrote {OUT.relative_to(ROOT)} — {total} components, {len(modifiers)} modifiers")
    print(f"Wrote {THEMES_OUT.relative_to(ROOT)} — {n_themes} daisyUI themes")
    print(f"Wrote {LLMS_OUT.relative_to(ROOT)} — llms.txt index")
    if JSON_OUT.parent.exists():
        print(f"Wrote {JSON_OUT.relative_to(ROOT)} — MCP data")


if __name__ == "__main__":
    main()
